[project]
name = "Canada Weather"
description = "Collect Weather Information in Canada"
version = "1.0.0"

[database]
[database.mysql]
host        = "mysql"
user        = "root"
password    = "root"
port        = 3306
db_name     = "weather_api"

[database.postgres]
host        = "hadoop_postgres"
user        = "jupyter"
password    = "jupyter"
port        = 5432
db_name     = "adv"

[database.mongodb]
host        = "mongo"
user        = ""
password    = ""
port        = 27017
db_name     = ""

[api]
[api.visualcrossing]
api_server  = "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/"
user        = "qianfan.cheng.cn@gmail.com"
key         = "3QMJPX68WQVXPD3QR28X8U5SA"

